/**
 * One command for a drawing session: start the editor, open it, and offer to
 * publish what you drew when you stop.
 *
 *   npm run draw                    # asks before pushing
 *   npm run draw -- --yes           # pushes without asking
 *   npm run draw -- --publish-only  # skip the editor, just publish what is drawn
 *
 * The editor writes straight into data/route-lines.geojson, so the only thing
 * that ever needs committing is that one file — routes-index.json and the
 * per-route JSON are regenerated by `npm run build` in CI.
 *
 * Pressing Ctrl-C stops the dev server and starts the publish step; it does not
 * abandon your work, which is already on disk by then.
 */

import { spawn, spawnSync } from 'node:child_process';
import { createInterface } from 'node:readline/promises';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { stdin, stdout } from 'node:process';

const PORT = 5173;
const REPO = resolve(import.meta.dirname, '..', '..');
const LINES = resolve(REPO, 'data', 'route-lines.geojson');
const AUTO_YES = process.argv.includes('--yes');
const PUBLISH_ONLY = process.argv.includes('--publish-only');
const ELEVATE = process.argv.includes('--elevate');

const git = (...args) =>
  spawnSync('git', args, { cwd: REPO, encoding: 'utf-8' }).stdout?.trim() ?? '';

/** routeId -> title, so the commit message names the route rather than a slug. */
function titles() {
  const index = resolve(REPO, 'app', 'static', 'data', 'routes-index.json');
  if (!existsSync(index)) return new Map();
  return new Map(
    JSON.parse(readFileSync(index, 'utf-8')).map((e) => [e.id, e.title])
  );
}

/** The routes with a line in a given version of the file. */
function drawnIn(text) {
  if (!text.trim()) return new Set();
  try {
    return new Set(JSON.parse(text).features.map((f) => f.properties.routeId));
  } catch {
    return new Set();
  }
}

function describeChange() {
  const before = drawnIn(git('show', 'HEAD:data/route-lines.geojson'));
  const after = drawnIn(existsSync(LINES) ? readFileSync(LINES, 'utf-8') : '');
  const named = titles();
  const added = [...after].filter((id) => !before.has(id));
  const removed = [...before].filter((id) => !after.has(id));
  const kept = [...after].filter((id) => before.has(id));
  return { added, removed, kept, named, total: after.size };
}

function commitMessage({ added, removed, named }) {
  const name = (id) => named.get(id) ?? id;
  if (added.length === 1 && !removed.length) return `data: draw the line up ${name(added[0])}`;
  if (added.length > 1 && !removed.length) return `data: draw lines for ${added.length} routes`;
  if (!added.length && removed.length) return `data: remove ${removed.length} drawn line(s)`;
  return 'data: redraw route lines';
}

async function publish() {
  const dirty = git('status', '--porcelain', 'data/route-lines.geojson');
  if (!dirty) {
    console.log('\nNothing drawn this session — nothing to publish.');
    return;
  }

  const change = describeChange();
  const name = (id) => change.named.get(id) ?? id;
  console.log('\n' + '─'.repeat(60));
  if (change.added.length) console.log(`  drawn:    ${change.added.map(name).join(', ')}`);
  if (change.removed.length) console.log(`  removed:  ${change.removed.map(name).join(', ')}`);
  if (change.kept.length) console.log(`  redrawn:  ${change.kept.map(name).join(', ')}`);
  console.log(`  the file now holds lines for ${change.total} route(s).`);
  console.log('─'.repeat(60));

  if (!AUTO_YES) {
    const rl = createInterface({ input: stdin, output: stdout });
    // Pushing deploys: the site rebuilds and these lines go live in ~5 minutes.
    const answer = (await rl.question('Commit and push to the live site? [y/N] ')).trim();
    rl.close();
    if (answer.toLowerCase() !== 'y') {
      console.log('Left uncommitted. `git diff data/route-lines.geojson` to see it.');
      return;
    }
  }

  const message = commitMessage(change);
  for (const args of [
    ['add', 'data/route-lines.geojson'],
    ['commit', '-m', message],
    ['push', 'origin', 'HEAD']
  ]) {
    const step = spawnSync('git', args, { cwd: REPO, stdio: 'inherit' });
    if (step.status !== 0) {
      console.error(`\ngit ${args[0]} failed — nothing further was pushed.`);
      process.exit(step.status ?? 1);
    }
  }
  console.log(`\nPushed: ${message}`);
  console.log('The site rebuilds and deploys in about five minutes.');
}

function openBrowser(url) {
  const [cmd, args] =
    process.platform === 'win32'
      ? ['cmd', ['/c', 'start', '""', url]]
      : process.platform === 'darwin'
        ? ['open', [url]]
        : ['xdg-open', [url]];
  spawn(cmd, args, { detached: true, stdio: 'ignore' }).unref();
}

if (ELEVATE) {
  // Re-sample every line already in the file, for routes drawn before the DEM
  // was wired in. Writes through the same middleware path the editor uses, so
  // there is one implementation of "what a saved line looks like".
  console.error('Run this through the dev server instead: start `npm run draw`,');
  console.error('open a route, and press Save to re-sample it.');
  process.exit(1);
}

if (PUBLISH_ONLY) {
  await publish();
  process.exit(0);
}

const dev = spawn('npm', ['run', 'dev', '--', '--port', String(PORT)], {
  cwd: resolve(REPO, 'app'),
  stdio: ['inherit', 'pipe', 'inherit'],
  shell: process.platform === 'win32'
});

let opened = false;
dev.stdout.on('data', (chunk) => {
  const text = String(chunk);
  stdout.write(text);
  // Wait for Vite to say it is listening, rather than guessing at a delay.
  if (!opened && text.includes('Local:')) {
    opened = true;
    const url = `http://localhost:${PORT}/draw`;
    console.log(`\nOpening the editor at ${url}`);
    console.log('Draw, press Save, then Ctrl-C here when you are done.\n');
    openBrowser(url);
  }
});

let publishing = false;
process.on('SIGINT', async () => {
  if (publishing) return;
  publishing = true;
  dev.kill();
  await publish();
  process.exit(0);
});

dev.on('exit', async (code) => {
  if (publishing) return;
  publishing = true;
  if (code) console.error(`\nThe dev server exited with code ${code}.`);
  await publish();
  process.exit(code ?? 0);
});
